services:
  ns2-nam:
    build:
      context: .      # Path to the folder containing Dockerfile
      dockerfile: Dockerfile
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ./ns2-scripts:/home/ns2/scripts
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    platform: linux/amd64   # Only needed for Apple Silicon
